# --password-store=gnome

--enable-features=UseOzonePlatform,WaylandUsePortal,VaapiVideoDecodeLinuxGL,VaapiVideoEncoder
--ozone-platform=wayland
--ozone-platform-hint=auto

--enable-features=VaapiVideoDecoder,VaapiVideoEncode,VaapiVideoDecodeLinuxGL,VaapiVideoEncoder
--enable-features=WebRTCHwVP8Encoding,WebRTCHwVP9Encoding,VaapiVideoDecodeLinuxGL,VaapiVideoEncoder

--ignore-gpu-blocklist
--disable-gpu-driver-bug-workarounds
--use-gl=desktop
--enable-accelerated-video-decode
--enable-zero-copy

--disable-features=TranslateUI,OptimizationGuideModelDownloading,WaylandWpColorManagerV1
--disable-notifications
--disable-domain-reliability
